services:
  
  kredis:
    hostname: kredis
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - dragonflydata:/data

  postgres:
    image: postgres:15.0-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    container_name: postgres
    environment:
      - POSTGRES_USER=${PG_USER:-projectweb}
      - POSTGRES_PASSWORD=${PG_PASSWORD:-securePassproject}
      - POSTGRES_DB=project
    restart: unless-stopped
    profiles:
      - dev
  
  postgres-test:
    image: postgres:15.0-alpine
    volumes:
      - pg_data1:/var/lib/postgresql/data
    container_name: postgres-test
    environment:
      - POSTGRES_USER=${PG_USER:-projectweb}
      - POSTGRES_PASSWORD=${PG_PASSWORD:-securePassproject}
      - POSTGRES_DB=project
    command: -p 5439
    restart: unless-stopped
    profiles:
      - test

  todo:
    container_name: todo
    build:
      context: ./todo
    ports:
      - "5000:5000"
    volumes:
      - './todo:/src'
    environment:
      # set environment variables
      - REDIS_URL=redis://kredis:6379/0
      - DEV_DATABASE_URL=${DEV_DATABASE_URL:-postgresql+psycopg2cffi://projectweb:securePassproject@postgres:5432/project}
      # do not use this configuration on a production setting
      - TEST_DATABASE_URL=${TEST_DATABASE_URL:-postgresql+psycopg2cffi://projectweb:securePassproject@postgres-test:5439/project}

    command: python manage.py runserver
    depends_on:
      - kredis
    profiles:
      - test
      - dev


volumes:
  pg_data: {}
  pg_data1: {}
  dragonflydata:
